### ISSUE TITLE
USER STORY: ADD POST

### ISSUE THREAD

**Issue by AlmaBroman** [AlmaBroman/flea-finder-stockholm#19]
As a **registered user** I can **add posts** so that **I can interact with the website**

### Acceptance Criteria

- User is able to create post when registered and logged in to their account

### Tasks

- [x] Create Add Event page
- [x] Add Post View
- [x] Create url path
- [x] Post Form
- [x] Cloudinary Storage 
- [x] Flash message
