### ISSUE TITLE
USER STORY: MANAGE COMMENTS

### ISSUE THREAD

**Issue by AlmaBroman** [AlmaBroman/flea-finder-stockholm#20]
As a **Site Admin** I can **create, read, update and delete comments** so that **I can manage my blog content**

### Acceptance Criteria

- [x] Admin is able to create, update and delete comments

### Tasks

- [x] Add a comment model
- [x] configure admin panel
