### ISSUE TITLE
USER STORY: MANAGE CATEGORIEs

### ISSUE THREAD

**Issue by AlmaBroman** [AlmaBroman/flea-finder-stockholm#22]
As a **Site Admin** I can ** create, read, update and delete categories** so that ** I can manage my blog content**

### Acceptance Criteria

- [x] Admin is able to create, update and delete categories

### Tasks

- [x] Add a category model
- [x] Add category to post model 
- [x] build and configure admin panel
