### ISSUE TITLE
USER STORY: MANAGE POSTS

### ISSUE THREAD

**Issue by AlmaBroman** [AlmaBroman/flea-finder-stockholm#3]
As a **Site Admin** I can **create, read, update and delete posts** so that **I can manage my blog content**

### Acceptance Criteria

- [x] Admin is able to create, update and delete posts

### Tasks

- [x] Install Django Allauth
- [x] Add a post model
- [x] build and configure admin panel
